language: java
jdk:
  - oraclejdk8
install: mvn -X clean test install
sudo: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: senthil.retnaswamy@gmail.com
  password: pivotal123
  organization: Zone_None
  space: development
